### ISSUE TITLE
load swin-l error

### ISSUE THREAD

**Issue by WEIZHIHONG720** [hikvision-research/opera#27]
2023-02-09 22:14:31,674 - mmdet - INFO - Set random seed to 2013303624, deterministic: False
2023-02-09 22:14:33,716 - mmdet - INFO - load checkpoint from http path: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window7_224_22kto1k.pth
Traceback (most recent call last):
  File "./train.py", line 242, in <module>
    main()
  File "./train.py", line 216, in main
    model.init_weights()
  File "/media/workspace/weizhihong/code/opera/third_party/mmcv/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/media/workspace/weizhihong/code/opera/third_party/mmdetection/mmdet/models/backbones/swin.py", line 705, in init_weights
    if list(state_dict.keys())[0].startswith('module.'):
IndexError: list index out of range
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "./train.py", line 242, in <module>
  File "./train.py", line 242, in <module>
  File "./train.py", line 242, in <module>
            main()main()main()

  File "./train.py", line 216, in main
  File "./train.py", line 216, in main
  File "./train.py", line 216, in main
        model.init_weights()model.init_weights()    

model.init_weights()
  File "/media/workspace/weizhihong/code/opera/third_party/mmcv/mmcv/runner/base_module.py", line 117, in init_weights
  File "/media/workspace/weizhihong/code/opera/third_party/mmcv/mmcv/runner/base_module.py", line 117, in init_weights
  File "/media/workspace/weizhihong/code/opera/third_party/mmcv/mmcv/runner/base_module.py", line 117, in init_weights
            m.init_weights()m.init_weights()m.init_weights()

  File "/media/workspace/weizhihong/code/opera/third_party/mmdetection/mmdet/models/backbones/swin.py", line 705, in init_weights
  File "/media/workspace/weizhihong/code/opera/third_party/mmdetection/mmdet/models/backbones/swin.py", line 705, in init_weights
  File "/media/workspace/weizhihong/code/opera/third_party/mmdetection/mmdet/models/backbones/swin.py", line 705, in init_weights
            if list(state_dict.keys())[0].startswith('module.'):if list(state_dict.keys())[0].startswith('module.'):if list(state_dict.keys())[0].startswith('module.'):

IndexErrorIndexErrorIndexError: : : list index out of rangelist index out of rangelist index out of range

**Comment by Yamameeee** [comment]
You should add `convert_weights=True` to backbone config like official mmdet swin config.
