### ISSUE TITLE
DK-DETR training problem

### ISSUE THREAD

**Issue by Lukas-Ma1** [hikvision-research/opera#36]
Thank you for your dkdetr , I use the command: `CUDA_VISIBLE_DEVICES=0 bash tools/dist_train.sh configs/dk-detr/dkd_r50_70e_lvis.py 1 --work-dir ./train_dir` to train dk-detr，and there occurs a mistake:
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 238, in main
    meta=meta)
  File "/data/msy/opera/opera/apis/train.py", line 245, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/data/msy/opera/third_party/mmcv/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data/msy/opera/third_party/mmcv/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/data/msy/opera/third_party/mmcv/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/data/msy/opera/third_party/mmcv/mmcv/parallel/distributed.py", line 59, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/msy/opera/third_party/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/xd/anaconda3/envs/dkdetr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/msy/opera/third_party/mmcv/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/data/msy/opera/third_party/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/msy/opera/third_party/mmdetection/mmdet/models/detectors/single_stage.py", line 84, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/data/msy/opera/opera/models/dense_heads/soit_head.py", line 159, in forward_train
    outs = self(x, img_metas)
  File "/home/xd/anaconda3/envs/dkdetr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
**TypeError: forward() missing 1 required positional argument: 'text_feats'**

Why it notes me 'text_feats' is missed, I include text feat path in config file.

**Comment by Lukas-Ma1** [comment]
After this, can you give me an example of training command? I have some idea and I would like to modify your code. Thank you so much!

**Comment by Letitialky** [comment]
@Lukas-Ma1 I run into the same problem, did you solve it ?  If so, can you share the solution? Thank you!
